[package]
name = "sntpc"
version = "0.2.0"
description = "Library for making SNTP requests"
homepage = "https://github.com/vpetrigo/sntpc"
repository = "https://github.com/vpetrigo/sntpc"
readme = "README.md"
categories = ["date-and-time", ]
keywords = ["sntp", "ntp", "sntp-client", "ntp-client"]
license = "BSD-3-Clause"
authors = ["Vladimir Petrigo <taenaru@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
simple_logger = "1.4"
clap = "2.33"

[badges]
travis-ci = { repository = "vpetrigo/sntpc", branch = "master" }
