[package]
name = "sntpc"
version = "0.1.0"
description = "Library for making SNTP requests"
homepage = "https://github.com/vpetrigo/sntpc"
repository = "https://github.com/vpetrigo/sntpc"
readme = "README.md"
categories = ["date-and-time", ]
keywords = ["sntp", "ntp", "sntp-client", "ntp-client"]
license-file = "LICENSE.md"
authors = ["Vladimir Petrigo <taenaru@gmail.com>"]
edition = "2018"

[dependencies]

[badges]

travis-ci = { repository = "vpetrigo/sntpc", branch = "master" }
